### PR TITLE
Fix for stake when info is not present

### LINKED ISSUE #143: Can't stake on Shibuya
**Describe the bug**
When I try to stake on Shibuya I got error in browser console

**To Reproduce**
1. Switch to Shibuya network
2. Click Stake button on any dapp
3. Enter staking amount
4. Click Stake on dialog
5. Click F12 in browser and see the error

**Expected behavior**
> Polkadot js extension dialog should be displayed

**Screenshots**
image

### PR DESCRIPTION
**Pull request by bobo-kovacevic**
**Pull Request Summary**

Currently store is unable to get stake info on Shibuya, because of large number of stakers, which caused an issue with stake function.

Closes #143 
**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**This pull request makes the following changes:**

**Adds**
- stakeInfo validation
- disable stakeinfo loading on shibuya
- enabled claim when stakeinfo is not present
image

### CODE REVIEW

File: src/components/store/StakePanel.vue [hunk 1]
```diff
@@ -132,14 +132,19 @@ export default defineComponent({
...
-
-      if (ttlStakeAmount.lt(minStaking.value)) {
-        store.dispatch('general/showAlertMsg', {
-          msg: `The amount of token to be staking must greater than ${formattedMinStake.value} ${unit}`,
-          alertType: 'error',
-        });
-        return;
+
+      if (props.stakeInfo) {
+        const ttlStakeAmount = amount.add(props.stakeInfo?.yourStake.denomAmount);
```
Comment (hoonsubin) [inline src/components/store/StakePanel.vue:137]: you don't need the null check for `props.stakeInfo?` because of the above `if` condition

**Review by hoonsubin — APPROVED** [review]
LGTM
